# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 638c747e4ada55b3d68a9be3e09e97e4872960a36c1c74bf2aa62631fba4c7b810d007110b8628b4d7172ca9872942387186bf4dbfc1d0b6b051fd3dd73138aa

test:
  secret_key_base: 98ac667f3749ba6cd41f1109d22b715590014287bdb08b97d7b693cbc9230b3e8cd30f5cb13ccd4543db00bf6317c1f9198b0c78ae04526deefad52dbeb0dfed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
